블록 변수 수정 각 블록 생성자 생성
LearningForAll/MLLego pull request #12
Opened 2018-03-28 13:15 UTC by ChaeByunghoon

2018-03-29 11:42 UTC, hea9549 requested changes
src/main/java/Component/BlockComponent/InputBlock.java

여기서 InputBlock이 ActionListener를 impl 하는건 안맞눈거같음 InputBlock자체의 Action기능이아니라
InputBlock의 oepnFileExploreButton 에만 해당하는 리스너니까
1. InputBlock안에 innerclass로 OpenFileExploreButton용 Actionlitener를 생성하는것 아니면
2. OpenFileExplorerButton.addActionListener( )해서 익명클래스로 하든지 둘중 한 방법이 좋아보임!

나머진 좋은거같음

2018-03-29 12:59 UTC, ChaeByunghoon commented
ㅇㅋ 확인 근데 그게 구조적인 측면에서 그렇다는 거임? 원래 나는 2번 케이스처럼 짜긴하는데 여러 버튼이 있을때 2번 케이스 처럼 짜면 코드가 좀 더러워지더라고 그래서 이번에 이렇게 해본건데 궁금함!

2018-03-30 07:59 UTC, ChaeByunghoon commented
@hea9549  이슈반영 완료!

2018-03-31 05:32 UTC, hea9549 requested changes
BlockBatchModel 은 다시구상해봐야할듯? 블럭 배치가 List형대로 되지않을꺼야 Expandable때문에 약간 양방향 트리구조? 그런모양이나올듯  예를들어 이렇게
      Input
     Expandable
Layer   Layer  Layer
 ----Fully Con ---
         Trainig

내가 생각한것은  배치화면에 나타나는 블럭들이 컨트롤러에 리스트형태로 다 저장하고 (연결하지않아도)
연결관계들은 따로 블럭 내에 afterBlocks, beforeBlocks에 저장되는거지 그래서 registerNextBlock(), registerPreviousBlock() 괜찮은듯 ㅇㅇ

BlockBatchModel이 모델에 들어가야할지 컨트롤러에 들어가야할지는 구조잡기나름일듯

앗 저게 내가말한거랑 같은건가? 뭔가 헷갈리네

BlockBatchModel에 대한 용도 설명이 주석으로 잇엇으면 좋겟음 커밋내용이나

그리고 Block.java에 register~~~(); 이거말고 추가적으로 저번에 말한 isConnectable(Block obj) 이거 있으면 좋을듯 

register 내에서 로직으로 체크할수도잇지만 connectable한지만 확인하는거 자체도 필요할거같아서 예를들어 connectable 해야 gui상에서 자석기능 제공할테니까 그때는 register하지는않고 gui만보여주는거니까

그리고 register~~~();은 void말고 bool값으로 return 해주면좋을듯 블록연결에 실패할상황이 어떤상황이있을지 모르지만(예를들어 블록 최대개수라던지?) 그런것에대한 bool이있으면좋겟음 물론 이건 Exception으로 처리해도됨.

각 abstract에 메소드정읳할땐 설명 추가하는걸루하자
내꺼 MLCore interface보면 대충 감잡힐듯? 이건필수는아니고

결론
1. 블록 배치모델에대한 더 설명이필요. 내가생각한것과 같은건가?
2. Block.java에서 register~~~() bool로 리턴바꾸는거
3. Block.java에 isConnectable 있어야할듯?

2018-03-31 05:33 UTC, hea9549 commented
@ChaeByunghoon  Review 남김 체크해주세용

2018-03-31 13:13 UTC, lauren026 approved these changes

2018-03-31 14:29 UTC, ChaeByunghoon commented
Connectable 만들었는데 푸쉬를안함 참고로 connectable은 isNextConnectable랑 isPreviousConnectable 두 함수로 나누어 놨음 이게 블록순서에 따라 달라지는 것 같다고 판단해서 나누어놨음  register함수는 bool로 바꾸거나 Exception으로 내일 처리하겄음

블록 배치 모델은 일단 대충 해놓은거라 ㅇㅋㅇㅋ 수정해놓을게

지금 생각해보니 connectable에 인자 하나 넘겨서 이게 다음블록인지 이전 블록인지 넘겨주는거 있으면 될것 같긴함 굳이 next랑 Previous 안나누고도 근데 어떤게 더 좋은 구조인지는 잘 모르겄음 생각 말해주삼

2018-03-31 15:22 UTC, hea9549 commented
ㅇㅇ 1.0 풀받고 컨플릭트 풀고 푸시바람 @ChaeByunghoon

2018-04-01 11:45 UTC, hea9549 approved these changes

2018-04-01 11:45 UTC, merged